version: "3.9"
networks:
  JobTest:
    name: JobTest
    driver: bridge

services:
  app:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: JobTestApp
    working_dir: /var/www/html
    ports:
      - ${APP_PORT:-8000}:8000
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - JobTest
    volumes:
      - ./src:/var/www/html
      - ./docker/home:/home/www-data
    restart: unless-stopped
    command: [ "php", "artisan","serve", "--host=0.0.0.0"]