version: "3.9"
networks:
  JobTest:
    name: JobTest
    driver: bridge

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-nginx
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: JobTestServer
    ports:
      - ${NGINX_PORT:-80}:80
    networks:
      - JobTest
    volumes:
      - ./src:/var/www/html:delegated
    restart: unless-stopped
    links:
      - app

  app:
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: JobTestApp
    working_dir: /var/www/html
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - JobTest
    volumes:
      - ./src:/var/www/html
      - ./docker/home:/home/www-data
    restart: unless-stopped